<h2><?echo _('Terms of Use for www.preoday.com');?></h2>
<!--<p class="lead">Title 1");?></p>-->
<p><?echo _("Welcome to www.preoday.com. If you continue to browse and use this website or app you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern www.preoday.com's relationship with you in relation to this website and app.");?></p>
<p><?echo _("The term \"www.preoday.com\" or \"us\" or \"we\" refers to the owner of the website and app. The term \"you\" refers to the user or viewer of our website and app.");?></p>
<p><?echo _("The use of this website and app is subject to the following terms of use:");?><br/>
<?echo _("ALL PERSONS UNDER THE AGE OF 18 ARE DENIED ACCESS TO THIS WEBSITE AND APP. IF YOU ARE UNDER 18 YEARS OF AGE, IT IS UNLAWFUL FOR YOU TO VISIT, READ, OR INTERACT WITH THIS WEBSITE AND APP OR ITS CONTENTS IN ANY MANNER. THIS WEBSITE AND APP SPECIFICALLY DENIES ACCESS TO ANY INDIVIDUAL THAT IS COVERED BY THE CHILD ONLINE PRIVACY ACT (COPA) OF 1998.");?></p>
<p><?echo _("The content of the pages of this website and app is for your general information and use only. It is subject to change without notice.
Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website and app for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.");?></p>
<p><?echo _("Your use of any information or materials on this website or app is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website and app meet your specific requirements.");?></p>
<p><?echo _("This website and app contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, content, layout, look, appearance and graphics. Reproduction is prohibited.");?></p>
<p><?echo _("All trademarks reproduced in this website and app, which are not the property of, or licensed to the operator, are acknowledged on the website and app.");?></p>
<p><?echo _("Unauthorised use of this website and app may give to a claim for damages and/or be a criminal offence.");?></p>
<p><?echo _("From time to time this website and app may also include links to other website and apps. These links are provided for your convenience to provide further information. They do not signify that we endorse the website and app(s). We have no responsibility for the content of the linked website and app(s).");?></p>
<p><?echo _("Your use of this website or app and any dispute arising out of such use of the website or app is subject to the laws of United Kingdom.");?></p>
<p><?echo _("Revisions to this website and app Terms of Use without notice");?></p>
<p><?echo _("This Terms of Use for www.preoday.com is dynamic. It will continually change. You may not assume that it remains the same and you agree to check the policy each time you visit the site for changes. Unless, in the sole opinion of the website and app, this policy changes so drastically as to suggest a posted notification on the site or via email, you will receive no notification of changes to this TERMS AND CONDITIONS for www.preoday.com nor, under any circumstances, does this site promise notification. Your continued use of this site or app always evidences your acceptance of the TERMS AND CONDITIONS for www.preoday.com or any modifications.");?></p>
<p><?echo _("Contact Information");?><br/><a href="http://www.preoday.com">www.preoday.com</a></p>
<p><?echo _("Latest Update");?><br/><?echo _("This Terms of Use for www.preoday.com: 01 June 2013");?></p>
<a href="<?echo $_SESSION['path']?>/"><img src="<?echo $_SESSION['path']?>/img/logo.png" alt="<? echo _("PreoDay");?>"/></a>
<p><?echo _("Preoday has created a mobile e-commerce platform specifically for the global food service and hospitality industry. We work with leading brands, niche players and independents alike to improve customer experiences and drive efficiencies in the ordering process. We leverage cutting edge technology and deep industry expertise to connect you more closely with your loyal customers. Just as it should be.");?></p>
<p><?echo _("Contact us now to learn more at");?> <a href='mailto:hello@preoday.com'>hello@preoday.com</a></p>
<a class="close-reveal-modal">&#215;</a>