<?php session_start();  require_once('lang.php');?>

function _tr(str){
	var trans=Dictionary[str];
	return trans !==undefined ? trans : str;
} 

var Dictionary = { 
	"Sorry, but there's been an error processing your request.":<? echo json_encode(_("Sorry, but there's been an error processing your request.")) ?>,
	"Incorrect credentials or account does not exist.":<? echo json_encode(_("Incorrect credentials or account does not exist.")) ?>,
	"Success! Please check your email for further instructions.":<? echo json_encode(_("Success! Please check your email for further instructions.")) ?>,
	"Sorry, incorrect code.":<? echo json_encode(_("Sorry, incorrect code.")) ?>,
	"Your password has been reset.<br/>You will now be redirected to the login page.":<? echo json_encode(_("Your password has been reset.<br/>You will now be redirected to the login page.")) ?>,
	"Venue changes have been saved!":<? echo json_encode(_("Venue changes have been saved!")) ?>,
	"Uploaded!":<? echo json_encode(_("Uploaded!")) ?>,
	"Error uploading file":<? echo json_encode(_("Error uploading file")) ?>,
	"Incorrect Image File":<? echo json_encode(_("Incorrect Image File")) ?>,
	"App changes have been saved!":<? echo json_encode(_("App changes have been saved!")) ?>,
	"Choose a size":<? echo json_encode(_("Choose a size")) ?>,
	"Choose a flavour":<? echo json_encode(_("Choose a flavour")) ?>,
	"Choose a topping":<? echo json_encode(_("Choose a topping")) ?>,
	"Choose some extras":<? echo json_encode(_("Choose some extras")) ?>,
	"Choose a side dish":<? echo json_encode(_("Choose a side dish")) ?>,
	"Pick an option type":<? echo json_encode(_("Pick an option type")) ?>,
	"Yes, delete this section and all its contents!":<? echo json_encode(_("Yes, delete this section and all its contents!")) ?>,
	"No, go back.":<? echo json_encode(_("No, go back.")) ?>,
	"Choose a main":<? echo json_encode(_("Choose a main")) ?>,
	"Choose a side":<? echo json_encode(_("Choose a side")) ?>,
	"Choose a drink":<? echo json_encode(_("Choose a drink")) ?>,
	"Choose a curry":<? echo json_encode(_("Choose a curry")) ?>,
	"Choose a burger":<? echo json_encode(_("Choose a burger")) ?>,
	"Menu configuration has been saved!":<? echo json_encode(_("Menu configuration has been saved!")) ?>,
	"Choose a Collection Slot":<? echo json_encode(_("Choose a Collection Slot")) ?>,
	"Are you sure you want to delete this event? Note: all event data will be lost!":<? echo json_encode(_("Are you sure you want to delete this event? Note: all event data will be lost!")) ?>,
	"Yes, delete this event!":<? echo json_encode(_("Yes, delete this event!")) ?>,
	"Role":<? echo json_encode(_("Role")) ?>,
	"Are you sure you want to delete this user? Note: all user data will be lost!":<? echo json_encode(_("Are you sure you want to delete this user? Note: all user data will be lost!")) ?>,
	"Yes, delete this user!":<? echo json_encode(_("Yes, delete this user!")) ?>,
	"Username/email already exists":<? echo json_encode(_("Username/email already exists")) ?>,
	"User configuration has been saved!":<? echo json_encode(_("User configuration has been saved!")) ?>,
	"Select all menus":<? echo json_encode(_("Select all menus")) ?>,
	"Unselect all menus":<? echo json_encode(_("Unselect all menus")) ?>,
	"Select menu(":<? echo json_encode(_("Select menu(")) ?>,
	"# of # selected":<? echo json_encode(_("# of # selected")) ?>,
	"Are you sure you want to delete this outlet? Note: all outlet data will be lost!":<? echo json_encode(_("Are you sure you want to delete this outlet? Note: all outlet data will be lost!")) ?>,
	"Yes, delete this outlet!":<? echo json_encode(_("Yes, delete this outlet!")) ?>,
	"Outlet configuration has been saved!":<? echo json_encode(_("Outlet configuration has been saved!")) ?>,
	"These times have been applied to all days!":<? echo json_encode(_("These times have been applied to all days!")) ?>,
	"We still need some more information. Don't forget to fill out the remaining days of the week!":<? echo json_encode(_("We still need some more information. Don't forget to fill out the remaining days of the week!")) ?>,
	"Where should this meal deal appear?":<? echo json_encode(_("Where should this meal deal appear?")) ?>,
	"Choose a menu section":<? echo json_encode(_("Choose a menu section")) ?>,
	"Are you sure you want to delete this meal deal? Note: all associated data will be lost!":<? echo json_encode(_("Are you sure you want to delete this meal deal? Note: all associated data will be lost!")) ?>,
	"Yes, delete this meal deal!":<? echo json_encode(_("Yes, delete this meal deal!")) ?>,
	"All changes has been saved!":<? echo json_encode(_("All changes has been saved!")) ?>,
	"Are you sure you want to delete this menu? Note: all menu data will be lost!":<? echo json_encode(_("Are you sure you want to delete this menu? Note: all menu data will be lost!")) ?>,
	"Yes, delete this menu!":<? echo json_encode(_("Yes, delete this menu!")) ?>,
	"Sorry, incorrect password.":<? echo json_encode(_("Sorry, incorrect password.")) ?>,
	"Settings and Password has been saved!<br/>You will need to log in again with your new password to continue.":<? echo json_encode(_("Settings and Password has been saved!<br/>You will need to log in again with your new password to continue.")) ?>,
	"Settings have been saved!":<? echo json_encode(_("Settings have been saved!")) ?>,
	"Please select features you require":<? echo json_encode(_("Please select features you require")) ?>,
	"Select all":<? echo json_encode(_("Select all")) ?>,
	"Sorry, these password do not match. Please try again.":<? echo json_encode(_("Sorry, these password do not match. Please try again.")) ?>,
	"All the fields are required.":<? echo json_encode(_("All the fields are required.")) ?>,
	"Please fill in all the required fields.":<? echo json_encode(_("Please fill in all the required fields.")) ?>,
	"This Premium Feature will remain active on your account until the end of the current billing cycle. You can cancel this uninstall at any time. If you wish to reinstall this Premium Feature after it has been deactivated, simply click on the <span>reinstall</span> option.":<? echo json_encode(_("This Premium Feature will remain active on your account until the end of the current billing cycle. You can cancel this uninstall at any time. If you wish to reinstall this Premium Feature after it has been deactivated, simply click on the <span>reinstall</span> option.")) ?>,
	"Are you sure you want to uninstall this Premium Feature?":<? echo json_encode(_("Are you sure you want to uninstall this Premium Feature?")) ?>,
	"UNINSTALL":<? echo json_encode(_("UNINSTALL")) ?>,
	"Your free trial will be imediately canceled and you will no longer have access to this feature.":<? echo json_encode(_("Your free trial will be imediately canceled and you will no longer have access to this feature.")) ?>,
	"Are you sure you want to cancel this Free Trial? This action cannot be undone?":<? echo json_encode(_("Are you sure you want to cancel this Free Trial? This action cannot be undone?")) ?>,
	"This Premium Feature is currently canceled. A new charge will be made to your card before reinstalling this feature.":<? echo json_encode(_("This Premium Feature is currently canceled. A new charge will be made to your card before reinstalling this feature.")) ?>,
	"Are you sure you want to reinstall this Premium Feature?":<? echo json_encode(_("Are you sure you want to reinstall this Premium Feature?")) ?>,
	"REINSTALL":<? echo json_encode(_("REINSTALL")) ?>,
	"Error":<? echo json_encode(_("Error")) ?>,
	"PAYMENT METHOD":<? echo json_encode(_("PAYMENT METHOD")) ?>,
	"Your new Premium Feature is now live!":<? echo json_encode(_("Your new Premium Feature is now live!")) ?>,
	"You can manage subscriptions from your account settings page":<? echo json_encode(_("You can manage subscriptions from your account settings page")) ?>,
	"OK":<? echo json_encode(_("OK")) ?>,
	"New":<? echo json_encode(_("New")) ?>,
	"Returning":<? echo json_encode(_("Returning")) ?>,
	" orders":<? echo json_encode(_(" orders")) ?>,
	"Day of collection":<? echo json_encode(_("Day of collection")) ?>,
	"Before day of collection":<? echo json_encode(_("Before day of collection")) ?>,
	"CANCEL":<? echo json_encode(_("CANCEL")) ?>,
	"Your order is running 15 mins late":<? echo json_encode(_("Your order is running 15 mins late")) ?>,
	"Late Order":<? echo json_encode(_("Late Order")) ?>,
	"Your order is on its way":<? echo json_encode(_("Your order is on its way")) ?>,
	"En-route":<? echo json_encode(_("En-route")) ?>,
	"There is a problem with your order. Please call us":<? echo json_encode(_("There is a problem with your order. Please call us")) ?>,
	"Call us":<? echo json_encode(_("Call us")) ?>,
	"Your address is out of our delivery zone":<? echo json_encode(_("Your address is out of our delivery zone")) ?>,
	"Out of zone":<? echo json_encode(_("Out of zone")) ?>,
	"Sorry, that item is out of stock":<? echo json_encode(_("Sorry, that item is out of stock")) ?>,
	"Out of stock":<? echo json_encode(_("Out of stock")) ?>,
	"Sorry, Your order has been rejected. Please call us":<? echo json_encode(_("Sorry, Your order has been rejected. Please call us")) ?>,
	"Successfully saved delivery settings.":<? echo json_encode(_("Successfully saved delivery settings.")) ?>,
	"Your card will be charged ":<? echo json_encode(_("Your card will be charged ")) ?>,
	" for this transaction. <br/> You may cancel this Premium Feature at any time from your account settings page.":<? echo json_encode(_(" for this transaction. <br/> You may cancel this Premium Feature at any time from your account settings page.")) ?>,
	"BUY":<? echo json_encode(_("BUY")) ?>,
	" DAY FREE TRIAL":<? echo json_encode(_(" DAY FREE TRIAL")) ?>,
	"Your card will not be charged for this transaction. <br/> You may cancel this Premium Feature at any time from your account settings page.":<? echo json_encode(_("Your card will not be charged for this transaction. <br/> You may cancel this Premium Feature at any time from your account settings page.")) ?>,
	"ACCOUNT SETTINGS":<? echo json_encode(_("ACCOUNT SETTINGS")) ?>,
	"RETURN TO STORE":<? echo json_encode(_("RETURN TO STORE")) ?>,
	"Please add a payment method to your account in order to subscribe to Premium Features":<? echo json_encode(_("Please add a payment method to your account in order to subscribe to Premium Features")) ?>,
	"ADD PAYMENT METHOD":<? echo json_encode(_("ADD PAYMENT METHOD")) ?>,
}
